version: "3.9"

services:
  go-web-app:
    build:
      context: .
      dockerfile: build/go-web-app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=${MONGO_PROTO:-mongodb}://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST:-mongo}:${MONGO_PORT:-27017}/${MONGO_DATABASE}?authSource=${MONGO_PARAMS}
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
